### ISSUE TITLE
Sidebar Menu in lobbies doesn't play well with other aspect ratios

### ISSUE THREAD

**Issue by MiningPickaxe** [DorCoMaNdO/Reactor-Essentials#10]
Issue moved from https://github.com/slushiegoose/Town-Of-Us/issues/42 to here:

When I run the game at my native 16:10 Aspect Ration (1920x1200) half of the menu is outside of the screen:
![image](https://user-images.githubusercontent.com/13851035/112044911-8929f080-8b4a-11eb-82d9-b66034415837.png)
When I manually change the resolution to 1920x1080 it works as intended.

**Comment by DorCoMaNdO** [comment]
This should now be addressed, the mod you're using uses a custom version of Essentials (without providing the code, which is against the license terms), so you sadly cannot update Essentials and keep using it because that mod will break, you'll have to wait for an update.
