### ISSUE TITLE
Option positions don't update in the menu

### ISSUE THREAD

**Issue by BOTHLine** [DorCoMaNdO/Reactor-Essentials#11]
I would love to have some method like "RecalculateOptionPositions" or something like that, where all the GameOptions reorder themselves.
Right now I do have a lot of empty spaces if I set MenuVisible to false.
Just something that iterates over all CustomOption entries and sets their new position (ignoring those which are invisible of course)

**Comment by DorCoMaNdO** [comment]
Could you post a video or image of what you mean? The position updates just fine for me.

**Comment by BOTHLine** [comment]
Issue was solved by using newest version of Essentials..
