### ISSUE TITLE
NullReferenceException when reopening the GameOptionsMenu

### ISSUE THREAD

**Issue by DorCoMaNdO** [DorCoMaNdO/Reactor-Essentials#12]
I get the following NullReferenceException when opening the GameOptionsMenu, after doing something specific:

- Open the GameOptionsMenu -> CustomOption will be created
- Close the GameOptionsMenu
- On the created CustomOption, set MenuVisible to false
- Reopen the GameOptionsMenu

After reopening the GameOptionsMenu, the NullReferenceException occurs (It should happen in GetGameOptions(lowestY)
`else if ((UnityEngine.Object) option.GameSetting != (UnityEngine.Object) null)
{
    ((UnityEngine.Component) option.GameSetting).gameObject.SetActive(true);
    optionBehaviourList.Add(option.GameSetting);
}`

Somehow the component/gameObject seems to be null.

> [Error  :    Detour] UnhollowerBaseLib.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
  at UnhollowerBaseLib.Il2CppException.RaiseExceptionIfNecessary (System.IntPtr returnedException) [0x00014] in <f4b054337e3641d0ae703d8d1584db73>:0
  at UnityEngine.Component.get_gameObject () [0x0002c] in <045cf7e91f5542268be1763686f1f2ad>:0
  at Essentials.Options.CustomOption.GetGameOptions (System.Single lowestY) [0x00063] in <1254f1b337aa418a8f8bfbd277af126f>:0
  at Essentials.Options.CustomOption+GameOptionsMenuPatchStart.Postfix (GameOptionsMenu __instance) [0x0002b] in <1254f1b337aa418a8f8bfbd277af126f>:0
  at (wrapper dynamic-method) GameOptionsMenu.DMD<GameOptionsMenu::Start>(GameOptionsMenu)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.(il2cpp -> managed) Start(intptr,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)

_Originally posted by @BOTHLine in https://github.com/DorCoMaNdO/Reactor-Essentials/issues/8#issuecomment-813006841_

**Comment by DorCoMaNdO** [comment]
Can't seem to reproduce. Please provide sample code.

**Comment by BOTHLine** [comment]
Oh I forgot to mention, I'm (still) using the 2021.3.5s version of everything.

I tried to break down everything as much as possible, I tried to wrap a "Page" System around your awesome Essentials CustomOption. In this Scenario I open the OptionsConsole, switch to the "Game"-Tab so the CustomOption gets created.
Then I close the Console, press Tab and repeat the same process. Then the NullReferenceException will be thrown.

When I press Tab while the "Game"-Tab is still open, the text in the top left corner changes (from Example Option 1 to Example Option 2 or vice versa) but the settings in the Menu don't switch. If I try to force them to change by adding a `UnityEngine.Object.FindObjectOfType<GameOptionsMenu>()?.Start();` to the TurnPage method at the end, then there stays a blank option when pressing Tab while the "Game"-Tab is open.
Which looks like this https://puu.sh/Hvj3B/8e9991bafd.png

```
using BepInEx;
using BepInEx.IL2CPP;
using Essentials.Options;
using HarmonyLib;
using Reactor;

[BepInPlugin(Id, Name, Version)]
[BepInProcess("Among Us.exe")]
[BepInDependency(ReactorPlugin.Id)]

public class Main : BasePlugin
{
    private const string  Id      = "gg.reactor.ExceptionExamplePlugin";
    private const  string  Name    = "Exception Example Plugin";
    private const  string  Version = "0.1";
    private       Harmony Harmony { get; } = new Harmony(Id);

    private static readonly CustomOption CustomOption1 = CustomOption.AddToggle("Example Option 1", true);
    private static readonly CustomOption CustomOption2 = CustomOption.AddToggle("Example Option 2", true);

    public override void Load()
    {
        CustomOption1.HudVisible = CustomOption1.MenuVisible = true;
        CustomOption2.HudVisible = CustomOption2.MenuVisible = false;

        Harmony.PatchAll();
    }

    public static void TurnPage()
    {
        bool visible = CustomOption1.HudVisible;

        CustomOption1.HudVisible = CustomOption1.MenuVisible = !visible;
        CustomOption2.HudVisible = CustomOption2.MenuVisible = visible;
    }
}
```

and TurnPage I can call via

```
using System.Collections.Generic;
using CrewOfSalem.Extensions;
using CrewOfSalem.Roles.Abilities;
using HarmonyLib;
using UnityEngine;

[HarmonyPatch(typeof(KeyboardJoystick))]
public static class UpdatePatch
{
    [HarmonyPatch(nameof(KeyboardJoystick.Update))]
    public static void Postfix(KeyboardJoystick __instance)
    {
        if (Input.GetKeyDown(KeyCode.Tab) && LobbyBehaviour.Instance != null)
        {
           Main.TurnPage();
        }
    }
}
```

**Comment by BOTHLine** [comment]
Fixed by using the newest version of Essentials.
