### ISSUE TITLE
PlayerCustomRpc could not be found

### ISSUE THREAD

**Issue by kfill420** [DorCoMaNdO/Reactor-Essentials#7]
Hello, 
On version 0.1.2 and 0.1.3, I have problems in the Essentials / Options / CustomOptions.Rpc.cs class.
Apparently a reference is missing for "PlayerCustomRpc <EssentialsPlugin, Rpc.Data>"
http://www.noelshack.com/2021-10-6-1615645388-pb-essentials-1.png

Can you help me please ?

I tried version 0.2.0 but had another problem:
http://www.noelshack.com/2021-10-6-1615645388-pb-essentials-2.png

**Comment by DorCoMaNdO** [comment]
Update Reactor

**Comment by kfill420** [comment]
I have already Reactor 0.2.9, the latest build..

**Comment by DorCoMaNdO** [comment]
Not.
