### ISSUE TITLE
Feature suggestion: dependencies

### ISSUE THREAD

**Issue by HakuTheWolfSpirit** [DorCoMaNdO/Reactor-Essentials#8]
Hi,

having a lot of options can make the options list very long very fast. Therefore dependencies might be useful where we can change an option and depending on that options values we show or hide other options. 

I don't need this right now but I'll just leave this as an idea here.

**Comment by DorCoMaNdO** [comment]
Already added as part of 0.2.0-dev builds with properties `MenuVisible` and `HudVisible`, ideally used with the `ValueChanged` event.

**Comment by HakuTheWolfSpirit** [comment]
![image](https://user-images.githubusercontent.com/35311793/111067878-8aae4580-84c6-11eb-916b-bff778e89d66.png)
This works for the options on the left. The options in the game menu can still not be disabled.
![image](https://user-images.githubusercontent.com/35311793/111069350-f693ac80-84cc-11eb-9966-f473365541af.png)

**Comment by DorCoMaNdO** [comment]
You set MenuVisible to false right? Does it work when you reopen the menu?

**Comment by HakuTheWolfSpirit** [comment]
When I close the menu and reopen it then all custom options disappear. Including the ones where the visibility wasn't toggled.

**Comment by DorCoMaNdO** [comment]
I'll take a look

**Comment by DorCoMaNdO** [comment]
Will be fixed with 0.2.0-dev.3, I'll also recommend using `CustomOption.RaiseValueChanged(false);` (on plugin load) after the update too, to update the option visibility to the default/currently selected value when first loading into the game.

**Comment by DorCoMaNdO** [comment]
Should be solved now, please let me know if you encounter any other issues.

**Comment by BOTHLine** [comment]
I get the following NullReferenceException when opening the GameOptionsMenu, after doing something specific:

- Open the GameOptionsMenu -> CustomOption will be created
- Close the GameOptionsMenu
- On the created CustomOption, set MenuVisible to false
- Reopen the GameOptionsMenu

After reopening the GameOptionsMenu, the NullReferenceException occurs (It should happen in GetGameOptions(lowestY)
`else if ((UnityEngine.Object) option.GameSetting != (UnityEngine.Object) null)
{
    ((UnityEngine.Component) option.GameSetting).gameObject.SetActive(true);
    optionBehaviourList.Add(option.GameSetting);
}`

Somehow the component/gameObject seems to be null.

> [Error  :    Detour] UnhollowerBaseLib.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
  at UnhollowerBaseLib.Il2CppException.RaiseExceptionIfNecessary (System.IntPtr returnedException) [0x00014] in <f4b054337e3641d0ae703d8d1584db73>:0
  at UnityEngine.Component.get_gameObject () [0x0002c] in <045cf7e91f5542268be1763686f1f2ad>:0
  at Essentials.Options.CustomOption.GetGameOptions (System.Single lowestY) [0x00063] in <1254f1b337aa418a8f8bfbd277af126f>:0
  at Essentials.Options.CustomOption+GameOptionsMenuPatchStart.Postfix (GameOptionsMenu __instance) [0x0002b] in <1254f1b337aa418a8f8bfbd277af126f>:0
  at (wrapper dynamic-method) GameOptionsMenu.DMD<GameOptionsMenu::Start>(GameOptionsMenu)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.(il2cpp -> managed) Start(intptr,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)
